name: bewise

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio@user
      MINIO_ROOT_PASSWORD: minio@secret
    ports:
      - 9000:9000
      - 9001:9001

  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - 11434:11434
  #   volumes:
  #     - .ollama:/root/.ollama

  # n8n:
  #   image: n8nio/n8n
  #   ports:
  #     - 5678:5678
  #   environment:
  #     - N8N_HOST=localhost
  #     - N8N_PORT=5678
  #     - N8N_PROTOCOL=http
  #     - NODE_ENV=production
  #   volumes:
  #     - .n8n:/home/node/.n8n
  #   depends_on:
  #     - postgres
  #     - redis
  #     - minio
  #     - ollama
