import type { Metadata } from "next";
import "./globals.css";
import { RootLayout } from "@/layouts/Root";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
