import { ReactNode } from "react";
import { AlignContent } from "@bewise/ui/type/AlignContent";
import { AlignItems } from "@bewise/ui/type/AlignItems";
import { AlignSelf } from "@bewise/ui/type/AlignSelf";
import { BackfaceVisibility } from "@bewise/ui/type/BackfaceVisibility";
import { BorderStyle } from "@bewise/ui/type/BorderStyle";
import { Color } from "@bewise/ui/type/Color";
import { ColorVariable } from "@bewise/ui/type/ColorVariable";
import { Cursor } from "@bewise/ui/type/Cursor";
import { Dimension } from "@bewise/ui/type/Dimension";
import { Direction } from "@bewise/ui/type/Direction";
import { Display } from "@bewise/ui/type/Display";
import { FlexDirection } from "@bewise/ui/type/FlexDirection";
import { FlexWrap } from "@bewise/ui/type/FlexWrap";
import { JustifyContent } from "@bewise/ui/type/JustifyContent";
import { Layout } from "@bewise/ui/type/Layout";
import { Opacity } from "@bewise/ui/type/Opacity";
import { Overflow } from "@bewise/ui/type/Overflow";
import { Position } from "@bewise/ui/type/Position";
import { Size } from "@bewise/ui/type/Size";
import { Transform } from "@bewise/ui/type/Transform";
import { Transition } from "@bewise/ui/type/Transition";

export type BoxStyle = {
  bbc?: ColorVariable | Color;
  bbs?: BorderStyle;
  bbw?: number;
  bc?: ColorVariable | Color;
  bfv?: BackfaceVisibility;
  bg?: ColorVariable | Color;
  blc?: ColorVariable | Color;
  blRadius?: number;
  bls?: BorderStyle;
  blw?: number;
  bottom?: Dimension;
  brc?: ColorVariable | Color;
  brRadius?: number;
  brs?: BorderStyle;
  brw?: number;
  bs?: BorderStyle;
  btc?: ColorVariable | Color;
  bts?: BorderStyle;
  btw?: number;
  bw?: number;
  content?: AlignContent;
  cursor?: Cursor;
  dir?: Direction;
  display?: Display;
  end?: Dimension;
  fBasis?: number | string;
  fDir?: FlexDirection;
  fGrow?: number;
  flex?: number;
  fShrink?: number;
  fWrap?: FlexWrap;
  gap?: Size;
  h?: Dimension;
  items?: AlignItems;
  justify?: JustifyContent;
  left?: Dimension;
  m?: Dimension;
  maxH?: Dimension;
  maxW?: Dimension;
  mb?: Dimension;
  minH?: Dimension;
  minW?: Dimension;
  ml?: Dimension;
  mr?: Dimension;
  mt?: Dimension;
  mx?: Dimension;
  my?: Dimension;
  opacity?: Opacity;
  overflow?: Overflow;
  p?: Dimension;
  pb?: Dimension;
  pl?: Dimension;
  position?: Position;
  pr?: Dimension;
  pt?: Dimension;
  px?: Dimension;
  py?: Dimension;
  radius?: number;
  ratio?: number;
  right?: Dimension;
  self?: AlignSelf;
  shadow?: number;
  start?: Dimension;
  tlRadius?: number;
  top?: Dimension;
  transform?: Transform[];
  transition?: Omit<Transition, "key"> | Transition[];
  trRadius?: number;
  w?: Dimension;
  z?: number;
};

export type BoxStyleKey = keyof BoxStyle;

export type BoxStyleProps = BoxStyle;

export type BoxProps = BoxStyleProps & {
  id?: string;
  hover?: BoxStyleProps;
  onPress?: () => void;
  onLayout?: (layout: Layout) => void;
  onLayoutChange?: (layout: Layout) => void;
  disabled?: boolean;
  hidden?: boolean;
  children?: ReactNode;
};
