import { marginHorizontalMapper } from "@bewise/ui/mappers/marginHorizontal";
import { marginVerticalMapper } from "@bewise/ui/mappers/marginVertical";
import { paddingHorizontalMapper } from "@bewise/ui/mappers/paddingHorizontal";
import { paddingVerticalMapper } from "@bewise/ui/mappers/paddingVertical";
import { shadowMapper } from "@bewise/ui/mappers/shadow";
import { transformMapper } from "@bewise/ui/mappers/transform";
import { cursorMapper } from "../mappers/cursor";

export const BOX_STYLE_MAP = {
  bbc: "borderBottomColor",
  bbw: "borderBottomWidth",
  bc: "borderColor",
  bec: "borderEndColor",
  beRadius: "borderBottomEndRadius",
  bew: "borderEndWidth",
  bfv: "backfaceVisibility",
  bg: "backgroundColor",
  blc: "borderLeftColor",
  blRadius: "borderBottomLeftRadius",
  blw: "borderLeftWidth",
  bottom: "bottom",
  brc: "borderRightColor",
  brRadius: "borderBottomRightRadius",
  brw: "borderRightWidth",
  bs: "borderStyle",
  bsc: "borderStartColor",
  bsRadius: "borderBottomStartRadius",
  bsw: "borderStartWidth",
  btc: "borderTopColor",
  btw: "borderTopWidth",
  bw: "borderWidth",
  content: "alignContent",
  cursor: cursorMapper,
  dir: "direction",
  display: "display",
  end: "end",
  fBasis: "flexBasis",
  fDir: "flexDirection",
  fGrow: "flexGrow",
  flex: "flex",
  fShrink: "flexShrink",
  fWrap: "flexWrap",
  gap: "gap",
  h: "height",
  items: "alignItems",
  justify: "justifyContent",
  left: "left",
  m: "margin",
  maxH: "maxHeight",
  maxW: "maxWidth",
  mb: "marginBottom",
  minH: "minHeight",
  minW: "minWidth",
  ml: "marginLeft",
  mr: "marginRight",
  mt: "marginTop",
  mx: marginHorizontalMapper,
  my: marginVerticalMapper,
  opacity: "opacity",
  overflow: "overflow",
  p: "padding",
  pb: "paddingBottom",
  pl: "paddingLeft",
  position: "position",
  pr: "paddingRight",
  pt: "paddingTop",
  px: paddingHorizontalMapper,
  py: paddingVerticalMapper,
  radius: "borderRadius",
  ratio: "aspectRatio",
  right: "right",
  self: "alignSelf",
  shadow: shadowMapper,
  start: "start",
  teRadius: "borderTopEndRadius",
  tlRadius: "borderTopLeftRadius",
  top: "top",
  transform: transformMapper,
  transition: "transition",
  trRadius: "borderTopRightRadius",
  tsRadius: "borderTopStartRadius",
  w: "width",
  z: "zIndex",
};
